site_name: My Docs

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: pink
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.edit

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AI-READI
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@aireadi.org
copyright: >
  Copyright &copy; 2024 AI-READI -
  <a href="#__consent">Change cookie settings</a>

repo_url: https://github.com/AI-READI/cds-specification
repo_name: AI-READI/cds-specification
edit_uri: edit/main/docs/

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true