site_name: CDS Specification

dev_addr: 127.0.0.1:3000

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: pink
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.edit
extra_css:
  - stylesheets/style.css

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AI-READI
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@aireadi.org
copyright: >
  Copyright &copy; 2024 AI-READI -
  <a href="#__consent">Change cookie settings</a>

repo_url: https://github.com/AI-READI/cds-specification
repo_name: AI-READI/cds-specification
edit_uri: edit/main/docs/

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - print-site

nav:
  - Introduction to the CDS: index.md
  - About this documentation: about.md
  - How to reference the CDS: referencing.md
  - CDS Specification: 
    - General principles: specification/general-principles.md
    - Root-level directory structure: specification/root-directory-structure.md
    - Datatype directory structure: specification/datatype-directory-structure.md
    - Root-level metadata files:
      - README.md: specification/root-metadata-files/readme.md
      - LICENSE.txt: specification/root-metadata-files/license.md
      - healthsheet.md: specification/root-metadata-files/healthsheet.md
      - CHANGELOG.md: specification/root-metadata-files/changelog.md
      - study_description.json: specification/root-metadata-files/study-description.md
      - dataset_description.json: specification/root-metadata-files/dataset-description.md
      - dataset_structure_description.json: specification/root-metadata-files/dataset-structure-description.md
      - participants.tsv and .json: specification/root-metadata-files/participants.md
  - Implementing the CDS:
    - Step-by-Step Guide: implementing-cds/step-by-step-guide.md
    - Templates: implementing-cds/templates.md
    - Examples: implementing-cds/examples.md
  - Design Rationale:
    - Overview: design-rationale/overview.md
  - Resources:
    - Changelog: resources/changelog.md
    - Governance: resources/governance.md
    - Feedback: resources/contributing.md